# -*- coding: utf-8 -*-
"""hello.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14w43exwPrh80BnSkwsEaZEFp5rhRHMw9
"""

print("Hello from Binder!")